# 2024/05/08 16:52:36 Timo

import sys
import os

import jieba
import argparse
import re
from pypinyin import pinyin, lazy_pinyin, Style

def regex_filter(text):
    '''
    Filter the text with regular expression
    Args:
        text: the text to be filtered
    Returns:
        the filtered text
    '''
    # Remove the English characters
    text = re.sub(r'[a-zA-Z]', '', text)
    # Remove the digits
    text = re.sub(r'\d', '', text)
    ## Remove the punctuation
    #text = re.sub(r'[^\u4e00-\u9fa5]', '', text)
    # Remove the spaces
    text = re.sub(r'\s', '', text)

    return text

def read_file(file_name):
    '''
    Load the Chinese text from file
    Args:
        file_name: the name of the file
    Returns:
        the text content of the file
    '''
    with open(file_name, 'r', encoding='utf-8') as f:
        text = f.read()
    
    text = regex_filter(text)

    return text

def convert_text2word(text):
    '''
    Convert the Chinese text to a dictionary
    Args:
        text: the Chinese text
    Returns:
        the dictionary
    '''
    # Load user defined dictionary
    jieba.load_userdict('user.dict')
    words = jieba.lcut(text)
    word_dict = {}
    for word in words:
        # if word is punctuation or empty
        if ( re.match(r'[^\u4e00-\u9fa5]', word)  or ( word == '')):
            continue
        else:
            if word in word_dict:
                word_dict[word] += 1
            else:
                word_dict[word] = 1

    return word_dict

def convert_word2dict(word_dict,output_file):
    '''
    Convert the word dictionary to rime dictionary
    Args:
        word_dict: the word dictionary generated by jieba
    Returns:
        the rime dictionary
    '''
    # Read the rime dict file header
    file_name = os.path.dirname(os.path.abspath(__file__))+ '/user.yaml'
    with open(file_name, 'r', encoding='utf-8') as f:
        header = f.read()
    rime_dict = {}
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(header)
        for word, count in word_dict.items():
            # Convert Chinese word to pinyin
            pinyin_list = lazy_pinyin(word)
            pinyin_str = ' '.join(pinyin_list)
            weight = 100
            f.write(f'{word}\t{pinyin_str}\t{weight}\n')
    
    return rime_dict

def args_parse():
    '''
    Parse the command line arguments
    Returns:
        the parsed arguments
    '''
    parser = argparse.ArgumentParser(
            description='Convert Chinese text to rime dict'
            )
    parser.add_argument(
            '--input',
            '-i',
            type=str,
            required=True,
            help='Name of the input text file'
            )
    parser.add_argument(
            '--output',
            '-o',
            type=str,
            required=False,
            help='Name of the output rime dict file'
            )

    return parser.parse_args()

def main():
    args = args_parse()

    text = read_file(args.input)
    word_dict = convert_text2word(text)
    
    convert_word2dict(word_dict, args.output)

if __name__ == '__main__':
    main()
